const usersTbl = require('./users_tbl/users_tbl.service.js');
const tapbidsrewardsTbl = require('./tapbidsrewards_tbl/tapbidsrewards_tbl.service.js');
const tapbidsTbl = require('./tapbids_tbl/tapbids_tbl.service.js');
const stproductsTbl = require('./stproducts_tbl/stproducts_tbl.service.js');
const rewardsclaimTbl = require('./rewardsclaim_tbl/rewardsclaim_tbl.service.js');
const rewardsTbl = require('./rewards_tbl/rewards_tbl.service.js');
const rewardptsTbl = require('./rewardpts_tbl/rewardpts_tbl.service.js');
const accountsTbl = require('./accounts_tbl/accounts_tbl.service.js');
const rbpTbl = require('./rbp_tbl/rbp_tbl.service.js');
const commisionTbl = require('./commision_tbl/commision_tbl.service.js');
const commsettingsTbl = require('./commsettings_tbl/commsettings_tbl.service.js');
const commtypeTbl = require('./commtype_tbl/commtype_tbl.service.js');
const countryTbl = require('./country_tbl/country_tbl.service.js');
const cscartTbl = require('./cscart_tbl/cscart_tbl.service.js');
const packageTbl = require('./package_tbl/package_tbl.service.js');
const provinceTbl = require('./province_tbl/province_tbl.service.js');
const raffleticketTbl = require('./raffleticket_tbl/raffleticket_tbl.service.js');
const retroprocessingTbl = require('./retroprocessing_tbl/retroprocessing_tbl.service.js');
const rsTbl = require('./rs_tbl/rs_tbl.service.js');
const rtinvoiceTbl = require('./rtinvoice_tbl/rtinvoice_tbl.service.js');
const stcartTbl = require('./stcart_tbl/stcart_tbl.service.js');
const stcategoryTbl = require('./stcategory_tbl/stcategory_tbl.service.js');
const stinvoiceTbl = require('./stinvoice_tbl/stinvoice_tbl.service.js');
const stinvoicedetailsTbl = require('./stinvoicedetails_tbl/stinvoicedetails_tbl.service.js');
const ststatusTbl = require('./ststatus_tbl/ststatus_tbl.service.js');
const sttypeTbl = require('./sttype_tbl/sttype_tbl.service.js');
const suretylogTbl = require('./suretylog_tbl/suretylog_tbl.service.js');
const tempuserTbl = require('./tempuser_tbl/tempuser_tbl.service.js');
const termsTbl = require('./terms_tbl/terms_tbl.service.js');
const ticketsTbl = require('./tickets_tbl/tickets_tbl.service.js');
const townTbl = require('./town_tbl/town_tbl.service.js');
const zipcodeTbl = require('./zipcode_tbl/zipcode_tbl.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(usersTbl);
  app.configure(tapbidsrewardsTbl);
  app.configure(tapbidsTbl);
  app.configure(stproductsTbl);
  app.configure(rewardsclaimTbl);
  app.configure(rewardsTbl);
  app.configure(rewardptsTbl);
  app.configure(accountsTbl);
  app.configure(rbpTbl);
  app.configure(commisionTbl);
  app.configure(commsettingsTbl);
  app.configure(commtypeTbl);
  app.configure(countryTbl);
  app.configure(cscartTbl);
  app.configure(packageTbl);
  app.configure(provinceTbl);
  app.configure(raffleticketTbl);
  app.configure(retroprocessingTbl);
  app.configure(rsTbl);
  app.configure(rtinvoiceTbl);
  app.configure(stcartTbl);
  app.configure(stcategoryTbl);
  app.configure(stinvoiceTbl);
  app.configure(stinvoicedetailsTbl);
  app.configure(ststatusTbl);
  app.configure(sttypeTbl);
  app.configure(suretylogTbl);
  app.configure(tempuserTbl);
  app.configure(termsTbl);
  app.configure(ticketsTbl);
  app.configure(townTbl);
  app.configure(zipcodeTbl);
};
